compatible with the latest version of Cordova
dial-once/sdk-cordova pull request #2
Opened 2017-04-07 21:55 UTC by techarc

compatible with the latest version of Cordova

2017-04-11 13:56 UTC, Spring3 approved these changes

2017-04-11 13:59 UTC, jkernech requested changes
Aside from noted LGTM ! Commits should be squashed before merging

2017-04-11 13:59 UTC, jkernech commented on src/android/DialOnceBridge.java
> +            for (int r : grantResults) {
For more readability, I would rename `r` by `grantResult`

2017-04-11 14:06 UTC, mrister approved these changes

2017-04-11 15:54 UTC, webus approved these changes

2017-04-11 16:22 UTC, jkernech approved these changes
Please squash your commits and we are good to go !

2017-04-12 09:46 UTC, ykhatal approved these changes

2017-04-13 14:39 UTC, merged